<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0
        ];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings', ['login' => 'true', 'catalogLogin' => 'true'])?>" data-lightbox><?=$this->transEsc("hold_login")?></a>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings', ['catalogLogin' => 'true'])])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEscAttr('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<?php endif; ?>
<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=$this->context($this)->renderInContext(
      'RecordTab/holdingsils/electronic.phtml',
      ['holdings' => $holdings['electronic_holdings']]
  );?>
<?php endif; ?>

<?php // DbSbg: Show summarized holdings ?>
<?php if(isset($holdings['summarizedHoldings']) && !empty($holdings['summarizedHoldings'])): ?>
  <div class='holdings'>
    <h3><?=$this->transEsc('summarizedHoldings')?></h3>
    <?php
    $hasLibrary = empty(array_filter(array_column($holdings['summarizedHoldings'], 'library'))) ? false : true;
    $hasLocation = empty(array_filter(array_column($holdings['summarizedHoldings'], 'location'))) ? false : true;
    $hasCallnumber = empty(array_filter(array_column($holdings['summarizedHoldings'], 'callnumber'))) ? false : true;
    $hasCallnumberNotes = empty(array_filter(array_column($holdings['summarizedHoldings'], 'callnumber_notes'))) ? false : true;
    $hasHolsAva = empty(array_filter(array_column($holdings['summarizedHoldings'], 'holdings_available'))) ? false : true;
    $hasGaps = empty(array_filter(array_column($holdings['summarizedHoldings'], 'gaps'))) ? false : true;
    $hasHoldingsNotes = empty(array_filter(array_column($holdings['summarizedHoldings'], 'holdings_notes'))) ? false : true;
    ?>
    <table class="table table-striped">
        <tr>
            <?php if ($hasLibrary): ?><th><?=$this->transEsc('Library')?></th><?php endif; ?>
            <?php if ($hasLocation): ?><th><?=$this->transEsc('Location')?></th><?php endif; ?>
            <?php if ($hasCallnumber): ?><th><?=$this->transEsc('Call Number')?></th><?php endif; ?>
            <?php if ($hasCallnumberNotes): ?><th><?=$this->transEsc('callNumberNote')?></th><?php endif; ?>
            <?php if ($hasHolsAva): ?><th><?=$this->transEsc('summarizedHoldings')?></th><?php endif; ?>
            <?php if ($hasGaps): ?><th><?=$this->transEsc('gaps')?></th><?php endif; ?>
            <?php if ($hasHoldingsNotes): ?><th><?=$this->transEsc('holdingNote')?></th><?php endif; ?>
        </tr>
        <?php foreach($holdings['summarizedHoldings'] as $sumHolding): ?>
          <?php if ($sumHolding && !empty($sumHolding)): ?>
          <tr>
            <?php
            // DbSbg: Get subarray data
            $gaps = [];
            $callnumberNotes = [];
            $holdingsNotes = [];
            if ($data = $sumHolding['gaps']) {
                foreach ($data as $gap) {
                    $gaps[] = $gap;
                }
            }
            if ($data = $sumHolding['callnumber_notes']) {
                foreach ($data as $callnumberNote) {
                    $callnumberNotes[] = $callnumberNote;
                }
            }
            if ($data = $sumHolding['holdings_notes']) {
                foreach ($data as $holdingsNote) {
                    $holdingsNotes[] = $holdingsNote;
                }
            }
            // DbSbg: Transform subarray data to string
            $gaps = implode(', ', array_filter($gaps));
            $callnumberNotes = implode(', ', array_filter($callnumberNotes));
            $holdingsNotes = implode(', ', array_filter($holdingsNotes));
            ?>
            <?php if ($hasLibrary): ?><td><?=$this->transEscWithPrefix('library_', $sumHolding['library'])?></td><?php endif; ?>
            <?php if ($hasLocation): ?><td><?=$this->transEscWithPrefix('location_', $sumHolding['location'])?></td><?php endif; ?>
            <?php if ($hasCallnumber): ?><td><?=$this->escapeHtml($sumHolding['callnumber'])?></td><?php endif; ?>
            <?php if ($hasCallnumberNotes): ?><td><?=$this->escapeHtml($callnumberNotes)?></td><?php endif; ?>
            <?php if ($hasHolsAva): ?><td><?=$this->escapeHtml($sumHolding['holdings_available'])?></td><?php endif; ?>
            <?php if ($hasGaps): ?><td><?=$this->escapeHtml($gaps)?></td><?php endif; ?>
            <?php if ($hasHoldingsNotes): ?><td><?=$this->escapeHtml($holdingsNotes)?></td><?php endif; ?>
          </tr>
          <?php endif; ?>
        <?php endforeach; ?>
    </table>
  </div>
<?php endif; ?>

<?php foreach ($holdings['holdings'] ?? [] as $holding): ?>
<h3>
  <?php $locationText = $this->transEscWithPrefix('location_', $holding['location']); ?>
  <?php // DbSbg: Get the library of the holding ?>
  <?php $libraryText = $this->transEscWithPrefix('library_', $holding['library']); ?>
  <?php if ($holding['locationhref'] ?? false): ?>
    <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
    <?php // DbSbg: Display the library of the holding if it is set ?>
    <?php if ($libraryText && !empty($libraryText)): ?>
        (<?=$libraryText?>)
    <?php endif; ?>
  <?php else: ?>
    <?=$locationText?>
    <?php // DbSbg: Display the library of the holding if it is set ?>
    <?php if ($libraryText && !empty($libraryText)): ?>
        (<?=$libraryText?>)
    <?php endif; ?>
  <?php endif; ?>
</h3>
<table class="table table-striped">
  <caption class="sr-only"><?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?></caption>
  <?php // DbSbg: Check if we have data from Alma. ?>
  <?php
  $hasCallnumber = empty(array_filter(array_column($holding['items'], 'callnumber'))) ? false : true;
  $hasBarcode = empty(array_filter(array_column($holding['items'], 'barcode'))) ? false : true;
  // DbSbg: Check if there is at least one item policy that should be displayed
  $displayItemPolicyColumn = in_array(false, array_column($holding['items'], 'item_policy_hide'));
  $hasItemPolicy = empty(array_filter(array_column($holding['items'], 'item_policy_code'))) ? false : $displayItemPolicyColumn;
  $hasDescription = empty(array_filter(array_column($holding['items'], 'description'))) ? false : true;
  $hasItemNotes = empty(array_filter(array_column($holding['items'], 'item_notes'))) ? false : true;
  ?>
  <tr>
    <?php if ($hasCallnumber): ?><th><?=$this->transEsc('Call Number')?></th><?php endif; ?>
    <?php if ($hasBarcode): ?><th><?=$this->transEsc('Barcode')?></th><?php endif; ?>
    <?php if ($hasItemPolicy): ?><th><?=$this->transEsc('Exemplarrichtlinie')?></th><?php endif; ?>
    <?php if ($hasDescription): ?><th><?=$this->transEsc('Description')?></th><?php endif; ?>
    <?php if ($hasItemNotes): ?><th><?=$this->transEsc('ItemNotes')?></th><?php endif; ?>
    <th><?=$this->transEsc('Availability')?></th>
  </tr>
  <?php foreach ($holding['items'] as $row): ?>
    <?php
        try {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/' . $this->tab->getTemplate() . '.phtml',
                ['holding' => $row, 'hasCallnumber' => $hasCallnumber, 'hasBarcode' => $hasBarcode,
                'hasItemPolicy' => $hasItemPolicy, 'hasDescription' => $hasDescription, 'hasItemNotes' => $hasItemNotes]
            );
        } catch (Exception $e) {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/standard.phtml',
                ['holding' => $row, 'hasCallnumber' => $hasCallnumber, 'hasBarcode' => $hasBarcode,
                'hasItemPolicy' => $hasItemPolicy, 'hasDescription' => $hasDescription, 'hasItemNotes' => $hasItemNotes]
            );
        }
    ?>
  <?php endforeach; ?>
  <?php if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <?php foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<?php endforeach; ?>
<?php if (!empty($holdings['total']) && $paginator = $this->tab->getPaginator($holdings['total'], $holdings['page'], $holdings['itemLimit'])): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>


<?php // DbSbg: No holdings available?>
<div class='holdings noHoldings'>
<?php // DbSbg: Check if there are no holdings (or URLs - uncomment below) ?>
  <?php if (empty($holdings['holdings']) /*&& empty($urls)*/ && empty($holdings['summarizedHoldings'])): ?>
    <h3><?=$this->transEsc("holdingNote")?>:</h3>
    <div class="padding-online-content">
        <?php // DbSbg: Show information that there are no holdings ?>
        <h4><?=$this->transEsc('NoHoldingsExist')?></h4>
    </div>
  <?php endif; ?>
</div>

