<h1>Impressum</h1>

<p>
  Die <strong>d|b|s Diözesanbibliothek Salzburg</strong> hat Bestände und Büros an
  zwei Standorten:<br />
  <br />
  Archiv der Erzdiözese Salzburg:<br />
  Kapitelplatz 3 | 5020 Salzburg<br />
  Tel.: +43-(0)662-8047-1502<br />
  <br />
  Priesterhaus der Erzdiözese Salzburg:<br />
  Dreifaltigkeitsgasse 14 | 5024 Salzburg<br />
  Tel.: +43-(0)662-8047-1520<br />
  <br />
  Für weitere Informationen oder Fragen setzen Sie sich bitte mit der <strong>d|b|s
  Diözesanbibliothek Salzburg</strong> in Kontakt:
  <a href="mailto:bibliothek@archiv.kirchen.net">bibliothek@archiv.kirchen.net</a>
</p>


<h3>Zweck der Webpräsenz:</h3>
<p>
  <a href="https://www.kirchen.net" target="_blank">www.kirchen.net</a> sowie die
  Seiten der Pfarren und Einrichtungen der Erzdiözese Salzburg sind Teil des
  offiziellen Internetportals der Katholischen Kirche Salzburg. Dieses Informations-
  und Kommunikationsorgan berichtet täglich aktuell über Neuigkeiten aus den Pfarren
  und Organisationseinheiten der Erzdiözese Salzburg. Die Website informiert, stellt
  zur Diskussion, bietet konkrete Hilfestellungen für ein Leben aus dem Glauben und
  lädt zur Kommunikation ein.
</p>

<h3>Für den Inhalt verantwortlich:</h3>
<p>
  Für den Inhalt von Pfarrhomepages und Homepages kirchlicher Einrichtungen auf dem
  Server der Katholischen Kirche Salzburg ist die jeweilige Pfarre bzw. Einrichtung
  selbst verantwortlich.
</p>
 
<h3>Rechtliche Hinweise:</h3>
<p>
  <h4>Copyright:</h4>
  <p>
    Der Inhalt dieser Homepage ist urheberrechtlich geschützt. Die Informationen sind
    nur für die persönliche Verwendung bestimmt. Jede weitergehende Nutzung,
    insbesondere die Speicherung in Datenbanken, eine Vervielfältigung und jede Form
    von gewerblicher Nutzung sowie die Weitergabe an Dritte - auch in Teilen oder in
    überarbeiteter Form - ohne Zustimmung der jeweiligen Organisation ist untersagt.
    © Erzdiözese Salzburg
  </p>

  <h4>Haftungsausschluss:</h4>
  <p>
    Im Hinblick auf die technischen Eigenschaften des Internets kann keine Gewähr für
    die Authentizität, Richtigkeit und Vollständigkeit der im Internet zur Verfügung
    gestellten Informationen übernommen werden. Es wird auch keine Gewähr für die
    Verfügbarkeit oder den Betrieb der gegenständlichen Homepage und ihrer Inhalte
    übernommen. Jede Haftung für unmittelbare, mittelbare oder sonstige Schäden,
    unabhängig von deren Ursachen, die aus der Benutzung oder Nichtverfügbarkeit der
    Daten und Informationen dieser Homepage erwachsen, wird, soweit rechtlich
    zulässig, ausgeschlossen. Wir distanzieren uns ausdrücklich vom Inhalt verlinkter
    Seiten und können für den Inhalt solcher Seiten keine Haftung übernehmen.
  </p>

  <h4>Datenschutz:</h4>
  <p>
    Hier geht es zur <a href="/Content/privacy">Datenschutzerklärung</a>.
  </p>

  <h4>Barrierefreiheit:</h4>
  <p>
    Die Erzdiözese Salzburg ist um eine möglichst barrierefreie Zugänglichkeit ihres
    Internetangebotes bemüht. Die WAI-Richtlinien (WCAG 2.0) werden berücksichtigt.
    Wir verzichten weitestgehend auf Technologien, die eine Nutzung unserer Seiten
    erschweren oder gar unmöglich machen. Wo dies nicht gelingt, versuchen wir
    Alternativen anzubieten, um niemanden von Informationen auszuschließen. Wir sind
    selbstverständlich laufend um weitere Verbesserungen bemüht und nehmen Ihre
    Anregungen dazu gerne unter
    <a href="mailto:office@komm.kirchen.net">office@komm.kirchen.net</a> entgegen.
  </p>

  <h4>Technische Realisierung:</h4>
  <p>
    Mag. Michael Birkner
  </p>
</p>