
<h1>Datenschutzerklärung</h1>

<h3>Geltungsbereich</h3>
<p>
  Diese Datenschutzerklärung soll die Nutzer der Website der Katholischen Kirche in
  Salzburg gemäß EU-Datenschutzgrundverordnung, Datenschutzgesetz und
  Telekommunikationsgesetz über die Art, den Umfang und den Zweck der Erhebung und
  Verwendung personenbezogener Daten durch den Websitebetreiber Erzdiözese Salzburg,
  Kapitelplatz 2, 5020 Salzburg, informieren.<br />
  <br />
  Der Websitebetreiber nimmt den Schutz Ihrer Daten sehr ernst und behandelt Ihre
  personenbezogenen Daten vertraulich und entsprechend der gesetzlichen
  Vorschriften.<br />
  <br />
  Bedenken Sie, dass die Datenübertragung im Internet grundsätzlich mit
  Sicherheitslücken bedacht sein kann. Ein vollumfänglicher Schutz vor dem Zugriff
  durch Fremde ist nicht realisierbar.
</p>

<h3>Zugriffsdaten</h3>
<p>
  Der Websitebetreiber bzw. Seitenprovider erhebt Daten über Zugriffe auf die Seite
  und speichert diese als „Server-Logfiles“ ab. Folgende Daten werden so
  protokolliert:<br />
  <ul>
    <li>Besuchte Website</li>
    <li>Uhrzeit zum Zeitpunkt des Zugriffes</li>
    <li>Menge der gesendeten Daten in Byte</li>
    <li>Quelle/Verweis, von welchem Sie auf die Seite gelangten</li>
    <li>Verwendeter Browser</li>
    <li>Verwendetes Betriebssystem</li>
    <li>Verwendete IP-Adresse</li>
  </ul>
  Die erhobenen Daten dienen lediglich statistischen Auswertungen und zur
  Verbesserung der Website. Der Websitebetreiber behält sich allerdings vor, die
  Server-Logfiles nachträglich zu überprüfen, sollten konkrete Anhaltspunkte auf eine
  rechtswidrige Nutzung hinweisen.
</p>

<h3>Cookies</h3>
<p>
  Diese Website verwendet Cookies. Dabei handelt es sich um kleine Textdateien,
  welche auf Ihrem Endgerät gespeichert werden. Ihr Browser greift auf diese Dateien
  zu. Durch den Einsatz von Cookies erhöht sich die Benutzerfreundlichkeit und
  Sicherheit dieser Website.<br />
  <br />
  Gängige Browser bieten die Einstellungsoption, Cookies nicht zuzulassen. Hinweis:
  Es ist nicht gewährleistet, dass Sie auf alle Funktionen dieser Website ohne
  Einschränkungen zugreifen können, wenn Sie entsprechende Einstellungen vornehmen.
</p>

<h3>Umgang mit personenbezogenen Daten</h3>
<p>
  Der Websitebetreiber erhebt, nutzt und gibt Ihre personenbezogenen Daten nur dann
  weiter, wenn dies im gesetzlichen Rahmen erlaubt ist oder Sie in die Datenerhebung
  einwilligen.<br />
  <br />
  Als personenbezogene Daten gelten sämtliche Informationen, welche dazu dienen, Ihre
  Person zu bestimmen und welche zu Ihnen zurückverfolgt werden können – also
  beispielsweise Ihr Name, Ihre E-Mail-Adresse und Telefonnummer.
</p>

<h3>Umgang mit Kontaktdaten</h3>
<p>
  Nehmen Sie mit dem Websitebetreiber durch die angebotenen Kontaktmöglichkeiten
  Verbindung auf, werden Ihre Angaben gespeichert, damit auf diese zur Bearbeitung
  und Beantwortung Ihrer Anfrage zurückgegriffen werden kann. Dasselbe gilt auch für
  die Online-Anmeldung. Ohne Ihre Einwilligung werden diese Daten nicht an Dritte
  weitergegeben.
</p>

<h3>Google Analytics</h3>
<p>
  Diese Website nutzt den Dienst „Google Analytics“ der Google Inc. (1600
  Amphitheatre Parkway Mountain View, CA 94043, USA) zur Analyse der Websitebenutzung
  durch Nutzer. Der Dienst verwendet „Cookies“ – Textdateien, welche auf Ihrem
  Endgerät gespeichert werden. Die durch die Cookies gesammelten Informationen
  werden im Regelfall an einen Google-Server in den USA gesandt und dort
  gespeichert.<br />
  <br />
  Auf dieser Website greift die IP-Anonymisierung: Die IP-Adresse der Nutzer wird
  innerhalb der Mitgliedsstaaten der EU und des Europäischen Wirtschaftsraum gekürzt.
  Durch diese Kürzung entfällt der Personenbezug Ihrer IP-Adresse. Im Rahmen der
  Vereinbarung zur Auftragsdatenvereinbarung, welche die Websitebetreiber mit der
  Google Inc. geschlossen haben, erstellt diese mit Hilfe der gesammelten
  Informationen eine Auswertung der Websitenutzung und der Websiteaktivität und
  erbringt mit der Internetnutzung verbundene Dienstleistungen.<br />
  <br />
  Sie haben die Möglichkeit, die Speicherung des Cookies auf Ihrem Gerät zu
  verhindern, indem Sie in Ihrem Browser entsprechende Einstellungen vornehmen.
  Es ist nicht gewährleistet, dass Sie auf alle Funktionen dieser Website ohne 
  Einschränkungen zugreifen können, wenn Ihr Browser keine Cookies zulässt.<br />
  <br />
  Weiters können Sie durch ein Browser-Plugin verhindern, dass die durch Cookies
  gesammelten Informationen (inklusive Ihrer IP-Adresse) an die Google Inc. gesendet
  und von der Google Inc. genutzt werden. Folgender Link führt Sie zu dem
  entsprechenden Plugin:
  <a href="https://tools.google.com/dlpage/gaoptout?hl=de" target="_blank">
  https://tools.google.com/dlpage/gaoptout?hl=de</a><br />
  <br />
  Alternativ verhindern Sie mit einem Klick auf diesen Link,
  [<a href="https://tools.google.com/dlpage/gaoptout?hl=de" target="_blank">
  https://tools.google.com/dlpage/gaoptout?hl=de</a>] dass Google Analytics innerhalb
  dieser Website Daten über Sie erfasst. Mit dem Klick auf obigen Link laden Sie ein
  „Opt-Out-Cookie“ herunter. Ihr Browser muss die Speicherung von Cookies also
  hierzu grundsätzlich erlauben. Löschen Sie Ihre Cookies regelmäßig, ist ein
  erneuter Klick auf den Link bei jedem Besuch dieser Website vonnöten.<br />
  <br />
  Hier finden Sie weitere Informationen zur Datennutzung durch die Google Inc.:
  <a href="https://support.google.com/analytics/answer/6004245?hl=de"
  target="_blank">https://support.google.com/analytics/answer/6004245?hl=de</a>
</p>

<h3>Nutzung von Social-Media-Plugins</h3>
<p>
  Diese Website verwendet Facebook Social Plugins, welches von der Facebook Inc.
  (1 Hacker Way, Menlo Park, California 94025, USA) betrieben wird. Erkennbar sind
  die Einbindungen an dem Facebook-Logo bzw. an den Begriffen „Like“, „Gefällt mir“,
  „Teilen“ in den Farben Facebooks (Blau und Weiß). Informationen zu allen
  Facebook-Plugins finden Sie im folgenden Link:
  <a href="https://developers.facebook.com/docs/plugins/" target="_blank">
  https://developers.facebook.com/docs/plugins/</a><br />
  <br />
  Das Plugin stellt eine direkte Verbindung zwischen Ihrem Browser und den
  Facebook-Servern her. Der Websitebetreiber hat keinerlei Einfluss auf die Natur
  und den Umfang der Daten, welche das Plugin an die Server der Facebook Inc.
  übermittelt. Informationen dazu finden Sie hier:
  <a href="https://www.facebook.com/help/186325668085084" target="_blank">
  https://www.facebook.com/help/186325668085084</a><br />
  <br />
  Das Plugin informiert die Facebook Inc. darüber, dass Sie als Nutzer diese Website
  besucht haben. Es besteht hierbei die Möglichkeit, dass Ihre IP-Adresse gespeichert
  wird. Sind Sie während des Besuchs auf dieser Website in Ihrem Facebook-Konto
  eingeloggt, werden die genannten Informationen mit diesem verknüpft.<br />
  <br />
  Nutzen Sie die Funktionen des Plugins – etwa indem Sie einen Beitrag teilen oder
  „liken“ – werden die entsprechenden Informationen ebenfalls an die Facebook Inc.
  übermittelt.<br />
  <br />
  Möchten Sie verhindern, dass die Facebook. Inc. diese Daten mit Ihrem
  Facebook-Konto verknüpft, loggen Sie sich bitte vor dem Besuch dieser Website bei
  Facebook aus.<br />
  <br />
  Weiters nutzt diese Website die „+1“-Schaltfläche von Google Plus. Betrieben wird
  diese von der Google Inc. (1600 Amphitheatre Parkway Mountain View, CA 94043, USA).
  Besuchen Sie eine Seite, welche die „+1“-Schaltfläche enthält, entsteht eine
  direkte Verbindung zwischen Ihrem Browser und den Google-Servern. Der
  Websitebetreiber hat daher keinerlei Einfluss auf die Natur und den Umfang der
  Daten, welche das Plugin an die Server der Google Inc. übermitteln. Klicken Sie
  auf den „+1“-Button, während Sie in Google + angemeldet sind, teilen Sie die
  Inhalte der Seite auf Ihrem öffentlichen Profil.<br />
  <br />
  Personenbezogene Daten werden laut der Google Inc. erst dann erhoben, wenn Sie auf
  die Schaltfläche klicken. Auch bei eingeloggten Google-Nutzern wird unter anderem
  die IP-Adresse gespeichert. Möchten Sie verhindern, dass die Google Inc. diese
  Daten speichert und mit Ihrem Konto verknüpft, loggen Sie sich bitte vor dem
  Besuch dieser Website aus.<br />
  <br />
  Informationen zur „+1“-Schaltfläche finden Sie hier:
  <a href="https://developers.google.com/+/web/buttons-policy" target="_blank">
  https://developers.google.com/+/web/buttons-policy</a>.<br />
  <br />
  Weiters nutzt diese Website Twitter-Schaltflächen. Betrieben werden diese von der
  Twitter Inc. (795 Folsom St., Suite 600, San Francisco, CA 94107, USA). Besuchen
  Sie eine Seite, welche eine solche Schaltfläche enthält, entsteht eine direkte
  Verbindung zwischen Ihrem Browser und den Twitter-Servern. Der Websitebetreiber
  hat daher keinerlei Einfluss über die Natur und den Umfang der Daten, welche das
  Plugin an die Server Twitter Inc. übermittelt.<br />
  <br />
  Gemäß der Twitter Inc. wird dabei allein Ihre IP-Adresse erhoben und
  gespeichert.<br />
  <br />
  Informationen zu dem Umgang mit personenbezogenen Daten durch die Twitter Inc.
  finden Sie hier:
  <a href="https://twitter.com/privacy?lang=de" target="_blank">
  https://twitter.com/privacy?lang=de</a>
</p>

<h3>Rechte des Nutzers: Auskunft, Berichtigung und Löschung</h3>
<p>
  Sie als Nutzer erhalten auf Antrag Ihrerseits kostenlose Auskunft darüber, welche
  personenbezogenen Daten über Sie gespeichert wurden. Sofern Ihr Wunsch nicht mit
  einer gesetzlichen Pflicht zur Aufbewahrung von Daten kollidiert, haben Sie ein
  Anrecht auf Berichtigung falscher Daten und auf die Sperrung oder Löschung Ihrer
  personenbezogenen Daten.
</p>