[Parent_Config]
relative_path = "../../../config/vufind/facets.ini"
override_full_sections = "Results,Advanced,Advanced_Settings,HomePage,ResultsTop"

[Results]
format             = Format
language           = Language
;language_txtF_mv = Language
subjectChainTopic_txtF_mv = "Subject"
author_facet       = Author
genre_facet        = Genre
publishDate        = "adv_search_year"

[ResultsTop]
subjectChainTopic_txtF_mv = "Suggested Topics"


[Author]
subjectChainTopic_txtF_mv = "Related Subjects"

[Advanced]
format             = Format
language           = Language
subjectChainTopic_txtF_mv = "Subject"

[Advanced_Settings]
facet_limit      = 100
orFacets = *
delimiter = "{{{_:::_}}}"
special_facets   = "illustrated,daterange"
translated_facets[] = format
translated_facets[] = callnumber-first:CallNumberFirst
translated_facets[] = language:Languages
;translated_facets[] = language_txtF_mv:Languages

[HomePage]
subjectChainTopic_txtF_mv = "Subject"
format             = Format
language           = Language
;language_txtF_mv = Language