[Parent_Config]
relative_path = "../../../config/vufind/RecordTabs.ini"
override_full_sections = "VuFind\RecordDriver\SolrMarc"

[VuFind\RecordDriver\SolrMarc]
tabs[Holdings] = HoldingsILS
tabs[Description] = Description
tabs[TOC] = TOC
; DbSbg: Removed tabs
;tabs[UserComments] = UserComments
; Commented out by default because only useful when simpleContainerLinks = true
; in config.ini:
;tabs[ComponentParts] = ComponentParts
tabs[Reviews] = Reviews
tabs[Excerpt] = Excerpt
tabs[Preview] = preview
tabs[HierarchyTree] = HierarchyTree
tabs[Map] = Map
tabs[Versions] = Versions
; DbSbg: Removed tabs
;tabs[Similar] = SimilarItemsCarousel
tabs[MARC] = StaffViewMARC
tabs[SOLR] = StaffViewArray
defaultTab = null
