[Parent_Config]
relative_path = "../../../config/vufind/searches.ini"
override_full_sections = "Basic_Searches,Advanced_Searches,Sorting"

[General]
highlighting = false
snippets = false

[Basic_Searches]
AllFields           = "All Fields"
Title               = Title
Author              = Author
Subject             = Subject
ISN                 = "ISBN/ISSN"

[Advanced_Searches]
AllFields           = adv_search_all
Title               = adv_search_title
Author              = adv_search_author
Subject             = adv_search_subject
ISN                 = adv_search_isn
publisher           = adv_search_publisher
Series              = adv_search_series
year                = adv_search_year
toc                 = adv_search_toc

[Sorting]
relevance = sort_relevance
year desc, title_sort asc = "sort_year"
year asc, title_sort asc = "sort_year asc"
author, title_sort asc = sort_author
title, author_sort asc = sort_title

[RawHiddenFilters]
; DbSbg: Don't show deleted records
0 = "-recordStatus_str:\"d\""

; DbSbg: List Solr fields with IDs that can be used in the record route
[RecordIdFields]
idFields = "id,acNo_txt"
